# application.yml
server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://localhost:3306/resource?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
jwt:
  apiSecretKey: Y3AIq+T7wSzomU7hV7NiifsnC9vPVs9B7OIWE5BSL+jxPYGNRSVcpqj9OfiA21CYeHcLqaTmylbxJF93R2si8w==
  expirationTime: 57600
  requestHeader: Authorization
  tokenPrefix: "Bearer "
logging:
  level:
    org.springframework: DEBUG